config/routes.rb
Grouppic::Application.routes.draw do
  resources :groups
  resources :topics
  resources :students

  root :to => "pages#index"
  match 'callback' => "pages#callback"
  match 'about' => "pages#about"
  match 'contact' => "pages#contact"

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :comment, :created_at, :id, :name
  has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :gpa, :grade, :id, :name
  has_and_belongs_to_many :groups

  def self.slc_list(token)
    header = Rails.application.config.slc_header.merge ({"Authorization" => "Bearer #{token}"})
    resp = RestClient.get(Rails.application.config.slc_base_url + "/rest/v1/students", header) {|resp, req, res| JSON.parse(resp)}
    #logger.debug "from Model debug 1: #{resp.inspect}"
    resp.map! {|s| s["name"]["firstName"] + " " + s["name"]["lastSurname"] }
    logger.debug "from Model debug 2: #{resp.inspect}"
    resp
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :grade, :id, :name, :subject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  respond_to :html, :js

  def index
    @oauthurl = "#{Rails.application.config.slc_base_url}/oauth/authorize?client_id=#{Rails.application.config.slc_client_id}&redirect_uri=#{Rails.application.config.base_url}/callback"
  end

  def about
  end

  def callback
    oauthurl = "#{Rails.application.config.slc_base_url}/oauth/token?code=#{params['code']}&grant_type=authorization_code&client_id=#{Rails.application.config.slc_client_id}&client_secret=#{Rails.application.config.slc_client_secret}&redirect_uri=#{Rails.application.config.base_url}/callback"
    respon = RestClient.get(oauthurl, Rails.application.config.slc_header) {|resp, req, res| JSON.parse(resp)}
    token = respon["access_token"]
    session[:token] = token
    redirect_to students_url
  end

  def contact
    @form = params[:cform] || []
    if(!@form.empty?) 
      if(@form[:name].blank? or @form[:email].blank? or @form[:subject].blank? or @form[:message].blank?)
        flash[:notice] = "Kindly fill in all the fields."
      else
        ContactMailer.send_contact(@form).deliver
        flash[:notice] = "Thank you for your message."
      end
    end
  end

  def verify
    if APP_CONFIG[:BETA_CODE].member? params[:code].to_s.downcase
      session[:code] = params[:code].to_s.downcase
      redirect_to root_url
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    respond_to :html, :js

  def index
    @students = Student.slc_list(session[:token])
    #@students = Student.all.sort_by {|s| s.gpa}
    @groups = Group.all
    while (@groups.count < 3) do
      @groups << Group.create({:name => "GROUP #{@groups.count + 1}"})
    end
    @groups = @groups.first(3)
    #@group = params[:groupno].blank? ? nil : params[:groupno].strip
    #@criteria = params[:criteria].blank? ? nil : params[:criteria].strip
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Comment</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.id %></td>
    <td><%= group.name %></td>
    <td><%= group.comment %></td>
    <td><%= group.created_at %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @group.id %>
</p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @group.comment %>
</p>

<p>
  <b>Created at:</b>
  <%= @group.created_at %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupPic</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    "application", "normalize", "main", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" %>
    <%= csrf_meta_tags %>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.8.2.min.js"><\/script>')</script>
      <script src="js/vendor/jquery-ui-1.8.24.custom.min.js"></script>
      <script src="js/plugins.js"></script>
      <script src="js/main.js"></script>
      <script>
        $(function() {
          $( "#sortable0, #sortable1, #sortable2, #sortable3" ).sortable({
            connectWith: ".connectedSortable"
          }).disableSelection();
        });
      </script>
  </head>

  <body>
    <div id="header">
      <div>
        <div id="logo"></div>
      </div>
    </div>
    <%= yield %>

    <br />
    <br />
    <div class="footer">
      Copyright &copy; 2012 GroupPic Shared Consortium
      <a href="/">Home</a> <a href="/about">About</a> <a href="/contact">Contact</a>
    </div>
    <br />
  </body>
</html>

app/views/pages/about.html.erb
<div class="content">
	<h1>The Grouppic Team</h1>
	<p>We are a bunch of experts from different fields who came together during the Shared Learning Collaborative (SLC) Camp Boston during Sept 29-30, 2012 to achieve a common goal - improving the quality of education for teachers and students</p>
	<ul>
		<li>Ana - Content Creater</li>
		<li>Dee - Technology Developer</li>
		<li>Erik -  Chief Executive</li>
		<li>Emeka - Product Management</li>
		<li>Jeff - Front-End Development</li>
		<li>Jiani - User Behavior Analyst</li>
		<li>Lucio - Designer</li>
		<li>Sook - Educator</li>
	</ul>
</div>

app/views/pages/contact.html.erb
<div class="content">
<h1>Contact Us</h1>
	<% if flash[:notice] %>
	     <div class="notice"><%= flash[:notice] %></div>
	<% else %>
	<p>Please fill in the form below to contact us:</p>
	<% end %>

<%= form_for :cform, :url => {:action => "contact" }, :html => {:class => "contactform"} do |f| %>
<table class="contactlabel">
   <tr><td><%= f.label :name, 'Name *' %>		</td><td> <%= f.text_field :name %> 	</td></tr>
   <tr><td><%= f.label :email, 'Email *' %>		</td><td> <%= f.text_field :email %> 	</td></tr>
   <tr><td><%= f.label :subject, 'Subject *' %>	</td><td> <%= f.text_field :subject %> 	</td></tr>
   <tr><td style="vertical-align:top; padding-top:5px;"><%= f.label :message, 'Message *' %> 	</td><td> <%= f.text_area :message %> 	</td></tr>
   <tr><td> </td><td><%= f.submit "Submit" %> </td></tr>
</table>
<% end %>

</div>

app/views/pages/index.html.erb
<div class="content">
  <p>Oftentimes teachers randomly select groups, losing the possibility of leveraging the group experience by combining students with complementary abilities or similar levels of comprehension of a subject.</p>
  <p>Even if objective criteria is used to select group members, teachers end up basing their decisions on assumptions or impressions about students due to limited access to student information.</p>
  <p>With GroupPic, teachers will be able to select the criteria they want to use to create groups for multiple projects in an easy, user-friendly environment, and add information about the groups performance so he/she has a record of which groups worked better and which didn't to further adapt to the next project.</p>
  <p>GroupPic helps teachers create a more homogeneous learning environment between groups by removing selection biases, as well as enhance learning by grouping students with similar or complementary learning styles.</p>
  <p>Smarter groups, better learning.</p>
  <p><%= link_to "Dive In", @oauthurl =%><p>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :grade %><br />
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :gpa %><br />
    <%= f.text_field :gpa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<!-- START Menu -->
<div id="menu">
    GROUPS:
    <select id="filter_groups" name="filter[groups]">
      <option value="2">2</option>
      <option value="3" selected="selected">3</option>
      <option value="4">4</option>
    </select>
    CRITERION:
    <select id="filter_criterion" name="filter[criterion]">
      <option value="gpa">GPA</option>
      <option value="name">Name</option>
      <option value="random">Random</option>
    </select>
</div>
<!-- END Menu -->
<div class="colmask leftmenu">
  <div class="col1">
    <div class="grouping">YOUR STUDENTS</div>
    <ul id="sortable0">
      <% @students.each do |student| %>
        <li>
        <!--
        <%= "#{student.name} (#{student.grade} : #{student.gpa})" if false %> 
        -->
        <%= student %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col2">
    <div>
      <% @groups.each_with_index do |group, i| %>
      <div style="float:left;width:<%= 100/@groups.count %>%">
        <div class="grouping"><%= group.name %></div>
        <ul id="sortable<%= i %>" class="connectedSortable"></ul>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @student.id %>
</p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Grade:</b>
  <%= @student.grade %>
</p>

<p>
  <b>GPA:</b>
  <%= @student.gpa %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :grade %><br />
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Subject</th>
    <th>Grade</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.id %></td>
    <td><%= topic.name %></td>
    <td><%= topic.subject %></td>
    <td><%= topic.grade %></td>
    <td><%= topic.description %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @topic.id %>
</p>

<p>
  <b>Name:</b>
  <%= @topic.name %>
</p>

<p>
  <b>Subject:</b>
  <%= @topic.subject %>
</p>

<p>
  <b>Grade:</b>
  <%= @topic.grade %>
</p>

<p>
  <b>Description:</b>
  <%= @topic.description %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>